README.md
models/Ingredient.js

It's simple, but I think it has all the things we need in an ingredient.

Add draft of ingredient model

---

README.md
models/Ingredient.js
server.js

Added server.js file so we can load it on localhost and see it tells us that we dont have any routes.

Config n server

---

seeds/ingredient_seeds.JSON

Some seeds, for what good they'll do without a recipe model. 
*shakes fists determinedly at outer space*

Add JSON seeds

---

.gitignore
db/schema.sql
package.json

Ran git init and added all the dependencies from the app files.

Add npm mods for running the server

---

.env
db/schema.sql
package.json
server.js

So we can load it and see that we have no routes.

Server runs on localhost

---

models/Instruction.js

Instruction model

---

models/sauceRecipeModel.js

take note on line 3 the ingredients path for the require ingredients is not entered. This will need to be edited to match the ingredients  requirements

built the model for sauce recipe model

---

models/Attributes.js
models/IngridientAttribute.js

adding attribute and ingredientattribute models

adding attribute and ingredientattribute models

---

seeds/ingredient_seeds.JSON
seeds/recipe_seeds.json

not sure if syntax are correct with using arrays placed in the ingredients and instructions. Would like feedback for verification.

Seed recipe

---

views/all.handlebars
views/layouts/main.handlebars

Created a template for the handlebars.main and the handlebars.all for the the project. Merely just a start of a fabulous template. Approve if you feel it will fit our project. We will add more as we go.

Handlebars main

---

seeds/attributes_seeds.js
seeds/baseIngredient_seeds.js
seeds/index.js
seeds/ingredientAttributes_seeds.js
seeds/ingredient_seeds.js
seeds/recipe_seeds.js

codys sorcery to resolve the bugs in front of our eyes by correcting the flaws in the importing of seeded packages

Fix model imports

---

models/Ingredient.js
models/index.js
models/sauceRecipeModel.js
seeds/index.js
seeds/ingredient_seeds.js

Codys changes to the models and the models index for the changes of the project. Cody psuedocoded the index.js file for further development

Add index to models

---

views/all.handlebars

Display recipe info on homepage

---

controllers/api/baseAttributeRoutes.js
controllers/api/baseIngredientRoutes.js
controllers/api/index.js
controllers/api/sauceRecipeRoutes.js
models/Attributes.js
models/BaseAttributes.js
models/BaseIngredient.js
models/index.js

Add attributes to base ingredients and base ingredients to sauce recipes.

Association revision

---

seeds/attributes_seeds.js
seeds/baseAttribute_seeds.js
seeds/index.js
seeds/recipe_seeds.js

New seed files. Server can be seeded without issues.

Seedfilechanges

---

controllers/api/sauceRecipeRoutes.js
views/recipe.handlebars

View recipe and ingredients

---

.env
public/main.css
seeds/baseIngredient_seeds.js
views/all.handlebars
views/layouts/main.handlebars
views/partials/recipe-details.handlebars
views/recipe.handlebars

I put the card around the sauce recipe info. The sauce recipe route connects to the sauce name anchor tag.

Finish homepage view from Wed night collab

---

.env
controllers/homeRoutes.js
models/userModel.js
public/main.css
public/signUp.js
server.js
views/layouts/main.handlebars
views/login.handlebars
views/signUp.handlebars

adding login and sign up

---

views/layouts/main.handlebars
views/partials/createSauce.handlebars
views/partials/recipe.handlebars

Not sure if this meets the target, is purely a modified moch up. Needs official testing.

Create sauce form

---

controllers/api/baseIngredientRoutes.js
seeds/baseAttribute_seeds.js
views/baseIngredient.handlebars
views/partials/recipe-details.handlebars

So we can click on the base ingredient and be presented with a view.

Add view for base ingredients
